[project]
type = "contract"
name = "defacto-protocol"
artifacts = "contracts/artifacts"

[deploy]
command = "cd contracts && python deploy.py"

[generate.smart_contract]
description = "Generate a new smart contract"
path = "contracts/src"

[algokit]
min_version = "v2.0.0"