# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: 77667703+Matthieuhakim@users.noreply.github.com
author_name: Matthieuhakim
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: de-news

