# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 77667703+Matthieuhakim@users.noreply.github.com
author_name: Matthieuhakim
preset_name: starter
project_name: de-news-frontend

